# Activate with: --spring.profiles.active=postgres
document-generator.persistence-mode=jdbc
spring.datasource.url=jdbc:postgresql://\
${DOCUMENT_GENERATOR_POSTGRES_HOST:localhost}:\
${DOCUMENT_GENERATOR_POSTGRES_PORT:5432}/\
${DOCUMENT_GENERATOR_POSTGRES_DATABASE:document_generator}
spring.datasource.username=${DOCUMENT_GENERATOR_POSTGRES_USER:document_generator}
spring.datasource.password=${DOCUMENT_GENERATOR_POSTGRES_PASSWORD:document_generator}
spring.datasource.driver-class-name=org.postgresql.Driver
