quarkus.http.port=8081
document-generator.persistence.mode=in-memory
quarkus.flyway.migrate-at-start=false
%postgres.document-generator.persistence.mode=jdbc
%postgres.quarkus.datasource.db-kind=postgresql
%postgres.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/document_generator
%postgres.quarkus.datasource.username=document_generator
%postgres.quarkus.datasource.password=document_generator
%postgres.quarkus.flyway.migrate-at-start=true
%postgres.quarkus.flyway.locations=db/migration
