quarkus.http.port=8081
document-generator.persistence.mode=in-memory
quarkus.flyway.migrate-at-start=false
%postgres.document-generator.persistence.mode=jdbc
%postgres.quarkus.datasource.db-kind=postgresql
%postgres.quarkus.datasource.jdbc.url=jdbc:postgresql://\
${DOCUMENT_GENERATOR_POSTGRES_HOST:localhost}:\
${DOCUMENT_GENERATOR_POSTGRES_PORT:5432}/\
${DOCUMENT_GENERATOR_POSTGRES_DATABASE:document_generator}
%postgres.quarkus.datasource.username=${DOCUMENT_GENERATOR_POSTGRES_USER:document_generator}
%postgres.quarkus.datasource.password=${DOCUMENT_GENERATOR_POSTGRES_PASSWORD:document_generator}
%postgres.quarkus.flyway.migrate-at-start=true
%postgres.quarkus.flyway.locations=db/migration
